-- MySQL Script generated by MySQL Workbench
-- Wed Nov 25 10:11:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ocorrencias_oltp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ocorrencias_oltp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ocorrencias_oltp` DEFAULT CHARACTER SET utf8 ;
USE `ocorrencias_oltp` ;

-- -----------------------------------------------------
-- Table `ocorrencias_oltp`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencias_oltp`.`cidade` ;

CREATE TABLE IF NOT EXISTS `ocorrencias_oltp`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocorrencias_oltp`.`bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencias_oltp`.`bairro` ;

CREATE TABLE IF NOT EXISTS `ocorrencias_oltp`.`bairro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bairro_cidade_idx` (`cidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_bairro_cidade`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `ocorrencias_oltp`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocorrencias_oltp`.`unidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencias_oltp`.`unidade` ;

CREATE TABLE IF NOT EXISTS `ocorrencias_oltp`.`unidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocorrencias_oltp`.`subunidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencias_oltp`.`subunidade` ;

CREATE TABLE IF NOT EXISTS `ocorrencias_oltp`.`subunidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  `unidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subunidade_unidade_idx` (`unidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_subunidade_unidade`
    FOREIGN KEY (`unidade_id`)
    REFERENCES `ocorrencias_oltp`.`unidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocorrencias_oltp`.`viatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencias_oltp`.`viatura` ;

CREATE TABLE IF NOT EXISTS `ocorrencias_oltp`.`viatura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocorrencias_oltp`.`tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencias_oltp`.`tipo` ;

CREATE TABLE IF NOT EXISTS `ocorrencias_oltp`.`tipo` (
  `codigo` VARCHAR(10) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocorrencias_oltp`.`ocorrencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencias_oltp`.`ocorrencia` ;

CREATE TABLE IF NOT EXISTS `ocorrencias_oltp`.`ocorrencia` (
  `id` INT UNSIGNED NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  `cidade_id` INT NOT NULL,
  `bairro_id` INT NOT NULL,
  `unidade_id` INT NOT NULL,
  `subunidade_id` INT NOT NULL,
  `viatura_id` INT NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_ocorrencia_tipo_idx` (`tipo` ASC) VISIBLE,
  INDEX `fk_ocorrencia_cidade_idx` (`cidade_id` ASC) VISIBLE,
  INDEX `fk_ocorrencia_bairro_idx` (`bairro_id` ASC) VISIBLE,
  INDEX `fk_ocorrencia_unidade_idx` (`unidade_id` ASC) VISIBLE,
  INDEX `fk_ocorrencia_subunidade_idx` (`subunidade_id` ASC) VISIBLE,
  INDEX `fk_ocorrencia_viatura_idx` (`viatura_id` ASC) VISIBLE,
  CONSTRAINT `fk_ocorrencia_tipo`
    FOREIGN KEY (`tipo`)
    REFERENCES `ocorrencias_oltp`.`tipo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ocorrencia_cidade`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `ocorrencias_oltp`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ocorrencia_bairro`
    FOREIGN KEY (`bairro_id`)
    REFERENCES `ocorrencias_oltp`.`bairro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ocorrencia_unidade`
    FOREIGN KEY (`unidade_id`)
    REFERENCES `ocorrencias_oltp`.`unidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ocorrencia_subunidade`
    FOREIGN KEY (`subunidade_id`)
    REFERENCES `ocorrencias_oltp`.`subunidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ocorrencia_viatura`
    FOREIGN KEY (`viatura_id`)
    REFERENCES `ocorrencias_oltp`.`viatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
