-- MySQL Script generated by MySQL Workbench
-- Wed Nov 25 10:09:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ocorrencias_olap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ocorrencias_olap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ocorrencias_olap` DEFAULT CHARACTER SET utf8 ;
USE `ocorrencias_olap` ;

-- -----------------------------------------------------
-- Table `ocorrencias_olap`.`local`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencias_olap`.`local` ;

CREATE TABLE IF NOT EXISTS `ocorrencias_olap`.`local` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bairro` VARCHAR(200) NOT NULL,
  `cidade` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocorrencias_olap`.`responsavel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencias_olap`.`responsavel` ;

CREATE TABLE IF NOT EXISTS `ocorrencias_olap`.`responsavel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subunidade` VARCHAR(200) NOT NULL,
  `unidade` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocorrencias_olap`.`tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencias_olap`.`tipo` ;

CREATE TABLE IF NOT EXISTS `ocorrencias_olap`.`tipo` (
  `codigo` VARCHAR(10) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocorrencias_olap`.`tempo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencias_olap`.`tempo` ;

CREATE TABLE IF NOT EXISTS `ocorrencias_olap`.`tempo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dia` TINYINT(2) NOT NULL,
  `dia_semana` TINYINT(2) NOT NULL,
  `mes` TINYINT(2) NOT NULL,
  `ano` INT NOT NULL,
  `hora` TINYINT(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocorrencias_olap`.`ocorrencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocorrencias_olap`.`ocorrencia` ;

CREATE TABLE IF NOT EXISTS `ocorrencias_olap`.`ocorrencia` (
  `id` INT UNSIGNED NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  `local_id` INT NOT NULL,
  `responsavel_id` INT NOT NULL,
  `tempo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_ocorrencia_tipo_idx` (`tipo` ASC) VISIBLE,
  INDEX `fk_ocorrencia_local_idx` (`local_id` ASC) INVISIBLE,
  INDEX `fk_ocorrencia_responsavel_idx` (`responsavel_id` ASC) VISIBLE,
  INDEX `fk_ocorrencia_tempo_idx` (`tempo_id` ASC) VISIBLE,
  CONSTRAINT `fk_ocorrencia_tipo`
    FOREIGN KEY (`tipo`)
    REFERENCES `ocorrencias_olap`.`tipo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ocorrencia_local`
    FOREIGN KEY (`local_id`)
    REFERENCES `ocorrencias_olap`.`local` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ocorrencia_responsavel`
    FOREIGN KEY (`responsavel_id`)
    REFERENCES `ocorrencias_olap`.`responsavel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ocorrencia_tempo`
    FOREIGN KEY (`tempo_id`)
    REFERENCES `ocorrencias_olap`.`tempo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
